Add method to fetch branches from a repo
sociomantic-tsunami/octod pull request #20
Opened 2017-06-12 17:24 UTC by mathias-baumann-sociomantic

2017-07-19 09:29 UTC, mihails-strasuns-sociomantic requested changes

2017-07-19 09:29 UTC, mihails-strasuns-sociomantic commented on src/octod/api/repos.d
> +    Tag[] branches ( )
Please rename `struct Tag` to `struct GitRef` and keep old name as deprecated alias if you want to reuse it for branches too.

2017-07-24 09:48 UTC, mathias-baumann-sociomantic commented
Renamed

2017-07-24 10:37 UTC, mathias-baumann-sociomantic commented
pushed changes

2017-07-24 10:49 UTC, mihails-strasuns-sociomantic approved these changes

2017-07-24 10:50 UTC, merged