Support explicit port in API base URL
sociomantic-tsunami/octod pull request #25
Opened 2017-08-22 17:21 UTC by mihails-strasuns-sociomantic

2017-08-22 17:22 UTC, mihails-strasuns-sociomantic commented
Wait a moment, needs one more tweak (to not ignore tls with custom port)

2017-09-12 15:44 UTC, mathias-baumann-sociomantic requested changes

2017-09-12 15:44 UTC, mathias-baumann-sociomantic commented on src/octod/core.d
> +            port = to!ushort(match[3][1..$]);
I am getting 
```
./octod/src/octod/core.d(142): Deprecation: vibe.data.serialization.to is not visible from module core
```

for this line

2017-09-12 16:03 UTC, mathias-baumann-sociomantic approved these changes

2017-09-12 16:03 UTC, merged